# Generated by Django 4.1.2 on 2022-11-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_rubric_spare_machine_ad_rubric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='name',
        ),
        migrations.AlterField(
            model_name='ad',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
